[package]
name = "hypixel_API"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.16", features=["json", "serde_json"] }
tokio = { version = "1.27.0", features=["full"] }
serde_json = "1.0.95"
serde_derive = "1.0.159"
serde = "1.0.159"
anyhow = "1.0.70"